import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by `payload generate:types`:
    'src/payload-types.ts',
    // Generated by `payload generate:importmap`:
    'src/app/(payload)/admin/importMap.js',
    // Third-party bundles and runtime uploads, not our source.
    'public/vendor/**',
    'public/media/**',
  ]),
])

export default eslintConfig
